org_unpackaged/unpackaged/objects/JiveSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>JiveSettings</label>
</CustomObject>

org_unpackaged/standard/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>UserName__c</fullName>
        <description>Updated by Business Center, pushed into Access</description>
        <inlineHelpText>The Business Center and Access user name</inlineHelpText>
        <label>User Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fs_facebook__c</fullName>
        <label>Facebook</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fs_industryExpertise__c</fullName>
        <label>Industry Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>Place holder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aerospace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apparel &amp; Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architectural and Design Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcasting, Music, &amp; Film</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Packaged Goods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy &amp; Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment &amp; Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gaming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government &amp; Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare Information Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality &amp; Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology Services</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>fs_linkedin__c</fullName>
        <label>LinkedIn</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fs_overview__c</fullName>
        <label>Overview</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fs_skills__c</fullName>
        <label>Skills</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fs_twitter__c</fullName>
        <label>Twitter</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/JiveToSFLeadUpdate.cls
global class JiveToSFLeadUpdate implements Database.Batchable<sObject>, Database.AllowsCallouts{
	global final String Query;
   	global final String Entity;
 
   	global JiveToSFLeadUpdate() {
      	Query='SELECT Id, FirstName, LastName, UserName__c, Email, Title, fs_industryExpertise__c, fs_skills__c, fs_overview__c, fs_facebook__c, fs_twitter__c, fs_linkedin__c ' +
              'FROM Lead WHERE UserName__c != Null';  
        Entity= 'Lead';
   	} 

   	global Database.QueryLocator start(Database.BatchableContext BC) {
        JiveSettings__c jivesetting = JiveSettings__c.getValues('Lock Trigger Batchable');
        jivesetting.Value__c = 'true';
        update jivesetting;
        
      	return Database.getQueryLocator(query);
   	}
   
   	global void execute(Database.BatchableContext BC, List<Lead> scope) {
        system.debug('scope:' + scope);
        
        List<Lead> leadsToUpdate = new List<Lead>();
        String JIVEPersonURL ;

        String JiveURL = JiveSettings__c.getValues('JiveURL').Value__c;
		system.debug('JiveURL:' + JiveURL);
        System.debug('scope: ' + scope);
        
        for(Lead leadRec : scope ) {   
            String jiveResponse = '';
     	
            JIVEPersonURL = JiveURL + '/people/username/'+ leadRec.UserName__c ;
            JIVEPersonURL +='?fields=ID,name,emails,tags,jive.profile.Title,';
            JIVEPersonURL +='jive.profile.Facebook,jive.profile.Twitter,jive.profile.LinkedIn,jive.profile.What%20do%20you%20do?,jive.username&filter=search()';
            
            system.debug('username:' + leadRec.UserName__c );
            try {
                HttpRequest req = new HttpRequest();
                req.setMethod('GET');
                String username = JiveSettings__c.getValues('Jive Username').Value__c; //'api01';
                String password = JiveSettings__c.getValues('Jive Password').Value__c;//'r8*&!$4*g40XpRsYUw0I';
                Blob headerValue = Blob.valueOf(username + ':' + password);
                String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
                req.setHeader('Authorization', authorizationHeader);
                req.setHeader('Accept', 'application/json');
                req.setEndPoint(JIVEPersonURL);
                
                Http http = new Http();
                
                 if (!Test.isRunningTest()) { 
                     HTTPResponse res = http.send(req);
                     
					if(res.getStatus() == 'OK') {
                        jiveResponse = res.getBody();
                        system.debug('body:' + jiveResponse);
                        
                        Lead leadResult = JiveToSFLeadUpdateHelper.processJiveResponse(leadRec, jiveResponse);
                        
                        if(leadResult != Null) {
                            leadsToUpdate.add(leadResult); 
                        }
                       
                    }
                 }
            }

            catch(Exception ex) {
                System.debug('Exception: ' + ex);   
            }
        }
        System.debug('leadsToUpdate: ' + leadsToUpdate);
        update leadsToUpdate;
    }
        
   	global void finish(Database.BatchableContext BC){ 
        JiveSettings__c jivesetting = JiveSettings__c.getValues('Lock Trigger Batchable');
        jivesetting.Value__c = 'false';
        update jivesetting;
   	}
    

        
    
    
}