org_unpackaged/standard/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>My_Biz_Office_User__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Status__c</fullName>
        <description>Flags where the account is in the sales process</description>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Converted Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy B2C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>ES_Client</fullName>
        <active>true</active>
        <description>All companies MBO ES Plans to do business with</description>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/My_Biz_Office_User__c.object
<CustomObject>
    <description>This object is used to display all MBO employees</description>
    <label>MBO User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MBO Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

org_unpackaged/unpackaged/classes/LogisticsControllerTest.cls
@isTest (seeAllData=False)
public class LogisticsControllerTest {

    static testMethod void test_setSL1(){
        // Setup Data
        //// Create MBO Users
        My_Biz_Office_User__c mboUser = new My_Biz_Office_User__c (Name='Test User');
        Insert mboUser;
        
        //// Create Account
        Id coRT = Util.getRecordTypeId('Account', 'ES_Client');
        Account acct = new Account (RecordTypeId=coRT, Name='Test Account', Activity_Status__c='Working', Account_Manager__c = mboUser.Id );
        Insert acct;
        
        //// Create Service Contracts
        List<ServiceContract> scList = new List<ServiceContract>();
        for(Integer i = 0; i < 250; i++){
            ServiceContract sc = new ServiceContract (Name = 'Service Contract'+i, Operations_Lead__c = mboUser.Id, Program_Coordinator__c = mboUser.Id, Service_Level__c = String.valueOf((i+1)/5) );
            scList.add(sc);
        }
        Insert scList;
        
        //// Build Query for Assertion
        List<ServiceContract> scAssert = [SELECT Id FROM ServiceContract WHERE Service_Level__c != '5'];
        
        // Test Controller
        //// Create Controller and List of Contracts
        LogisticsController controller = new LogisticsController();
        List<ServiceContract> getSC = controller.getServiceContracts();
        
        // Assert Controller
        //// Compare Assertion Query to Controller Contracts
        System.assert(scAssert.size() == getSC.size());
    }
}