org_unpackaged/standard/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activity_Status__c</fullName>
        <description>Flags where the account is in the sales process</description>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Converted Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy B2C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Company_Number__c</fullName>
        <description>The company number in the MBO CMS</description>
        <externalId>true</externalId>
        <inlineHelpText>Hidden</inlineHelpText>
        <label>Company Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fb_MBO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MBO Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>fs_wMProjID__c</fullName>
        <label>Work Market Project ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fs_wmCompanyId__c</fullName>
        <label>WM Company ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>ES_Client</fullName>
        <active>true</active>
        <description>All companies MBO ES Plans to do business with</description>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/My_Biz_Office_User__c.object
<CustomObject>
    <description>This object is used to display all MBO employees</description>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MBO User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MBO Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

org_unpackaged/standard/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>fn_pUnitCost__c</fullName>
        <label>Primary Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fs_pricingType__c</fullName>
        <label>Pricing Type</label>
        <picklist>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hourly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dual-rate Hourly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>fs_wMAssignmentID__c</fullName>
        <label>Work Market Assignment ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fs_wmCompanyId__c</fullName>
        <label>WM Company ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fs_woEnd__c</fullName>
        <inlineHelpText>Updated by the MBO System</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>fs_woStart__c</fullName>
        <inlineHelpText>Updated by the MBO System</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>rs_client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Updated by the MBO System</inlineHelpText>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>workOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Work_Order</fullName>
        <active>true</active>
        <businessProcess>Work Order</businessProcess>
        <description>This is a work order</description>
        <label>Work Order</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

org_unpackaged/unpackaged/classes/TestWorkMarketWorkOrderInsert.cls
@isTest
private class TestWorkMarketWorkOrderInsert {
    
    //Begin Helper Methods
    
    private static My_Biz_Office_User__c createMBOUser (){
        My_Biz_Office_User__c mboUser = new My_Biz_Office_User__c(
            Name = 'Sara Conde',
            Email__c = 'sconde@mbopartners.com',
            First_Name__c = 'Sara',
            Last_Name__c = 'Conde');
        insert mboUser;
        return mboUser;
    }
    
    private static Account createWMClient (String clientName, Id acctRtId, String companyId){
        Account wm = new Account(
            name = clientName,
            RecordTypeId = acctRtId,
            Type = 'Large Corporate',
            fb_MBO__c = TRUE,
            fs_wMProjId__c = string.valueOf(math.round(math.random()*(99999-11111))+11111),
            billingStreet = '123 Left Ln',
            billingCity = 'New York',
            billingState = 'NY',
            billingPostalCode = '10001',
            billingCountry = 'USA',
            Company_Number__c = string.valueOf(math.round(math.random()*(99999-11111))+11111),
            Activity_Status__c = 'Client',
            fs_wmCompanyId__c = companyId);
        insert wm;
        return wm;
    }   

    private static Account createWMAssociate (String fName, String lName, Id acctRtId, Id mboUser){
        Account assoc = new Account(
            firstName = fName,
            lastName = lName,
            RecordTypeId = acctRtId,
            personEmail = fName + '.' + lName+'@mbopartners.com',
            Phone = '7037936000',
            personMailingStreet = '123 Left Ln',
            personMailingCity = 'New York',
            personMailingState = 'NY',
            personMailingPostalCode = '10001',
            personMailingCountry = 'USA',
            Contact_Status__pc = 'Associate',
            Enrollment_Manager__pc = mboUser,
            Associate_Number__pc = string.valueOf(math.round(math.random()*(99999-11111))+11111),
            Associate_Status__pc = 'Active',
            Business_Manager__pc = mboUser);
        insert assoc;
        return assoc;
    }   

    private static Opportunity createOpportunity(String opName, Id assocId, String wmId, Id rtId, boolean b){
        System.debug('Associate Id: '+assocId);
        System.debug('wmId: '+wmId);
        Opportunity o = new Opportunity(
            name = opName,
            AccountId = assocId,
            fn_pUnitCost__c = 50.00,
            fs_woStart__c = Date.today(),
            fs_woEnd__c = Date.today()+5,
            CloseDate = Date.today()+5,
            StageName = 'Pending',
            fs_wmAssignmentId__c = '123456789',
            fs_pricingType__c = 'Flat Fee',
            fs_wmCompanyId__c = wmId,
            RecordTypeId = rtId, rs_client__c=null);

	        System.debug('Opportunity Id: '+o.Id);
	        System.debug('Opportunity Name: '+o.name);
	        System.debug('Opportunity Company Id: '+o.fs_wmCompanyId__c);
	        System.debug('Opportunity Account: '+o.accountId);
	        System.debug('Before Insert - Opportunity Client: '+o.rs_client__c);
        if(b){
            insert o;
            o = [select Id, Name, AccountId, fn_pUnitCost__c, fs_woStart__c, fs_woEnd__c, CloseDate, StageName, fs_wmAssignmentId__c, fs_pricingType__c, fs_wmCompanyId__c, RecordTypeId, rs_client__c from Opportunity where Id = :o.Id];
            System.debug('After Insert - Opportunity Client: '+o.rs_client__c);
            return o;
        }else{
            return o;
        }
    }

    //End Helper Methods
    
    
    //Create single opportunity and assign a client
    static testmethod void testClientAssignment(){
        test.startTest();
        //Populate any required data
        Id woId = util.getRecordTypeId('Opportunity','Work_Order');
        Id coId = util.getRecordTypeId('Account','ES_Client');
        Id assocId = util.getRecordTypeId('Account','Partners_Associate');
        My_Biz_Office_User__c mboUser = createMBOUser();
        System.debug('MBO User Id: '+mboUser.Id);
        Account wm = createWMClient('Work Market',coId,'1');
        System.Debug('Work Market Id: '+wm.Id);
        Account client = createWMClient('Client a',coId,'987654321');
        System.debug('Client Id: '+client.Id);
        Account assoc = createWMAssociate('John','Smith',assocId,mboUser.Id);
        System.Debug('Associate Id: '+assoc.Id);

        //Test to ensure the correct client is set
        Opportunity match = createOpportunity('New Job',assoc.Id, '987654321',woId,TRUE);
        System.debug('Opportunity Id: '+match.Id);
        System.debug('Opportunity Name: '+match.name);
        System.debug('Opportunity Company Id: '+match.fs_wmCompanyId__c);
        System.debug('Opportunity Account: '+match.accountId);
        System.debug('Opportunity Client: '+match.rs_client__c);
        test.stopTest();
        system.assertEquals(client.Id, match.rs_client__c);
    }

/*
    //Create single opportunity and assign Work Market
    static testmethod void testWorkMarketAssignment(){
        //Build test accounts and opportunities
        Account wm = createWMClient('Work Market','1');
        Account client = createWMClient('Client a','987654321');
        Opportunity mismatch = createOpportunity('New Job2', null, true);

        //Debug
        system.debug(wm);
        system.debug(client);
        system.debug(mismatch);
        
        //Test to ensure the correct client is set
        test.startTest();
        System.assertEquals(mismatch.rs_client__c, client.Id);
        test.stopTest();
    }
    
    //Create batch of opportunities with client or Work Market as client
    static testmethod void testBatchAssignment(){
        //Build test accounts
        Account wm = createWMClient('Work Market','1');
        Account client = createWMClient('Client a','987654321');
      
        //Build batch of opportunities
        List<Opportunity> opList = new List<Opportunity>();
        for(integer i =1;i<=250;i++){
            Opportunity opp = new Opportunity();
            if(math.mod(i,2)>0){
                opp = createOpportunity('Opportunity' + i, '987654321', false);
            }else{
                opp = createOpportunity('Opportunity' + i, null, false);
            }
            opList.add(opp);
        }
        insert opList;

        //Debug
        system.debug(wm);
        system.debug(client);
        system.debug(opList.size());
        system.debug(opList[10]);
                
        //Test that all opportunities have the right client set
        for(Opportunity o: opList){
            Test.startTest();
            system.assert(o.rs_client__c == client.Id || o.rs_client__c == wm.Id);
            Test.stopTest();
        }
    }
*/
}