org_unpackaged/standard/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBOAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used as a flag for adding a record to the connection center; used in the connection center</description>
        <inlineHelpText>Check this if this record is to send an update to the connection center</inlineHelpText>
        <label>MBO Access</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Feed__c.object
<CustomObject>
    <fields>
        <fullName>fs_description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fs_url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>rs_recipientAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Feeds</relationshipLabel>
        <relationshipName>Job_Feed_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rs_recipientLead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Job Feeds</relationshipLabel>
        <relationshipName>Job_Feed_Lead</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Feed</label>
    <nameField>
        <label>Job Feed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Feeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

org_unpackaged/unpackaged/objects/JiveSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>JiveSettings</label>
</CustomObject>

org_unpackaged/standard/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>MBOAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to grant the lead access to MBO Access.</description>
        <label>MBO Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <description>Updated by Business Center, pushed into Access</description>
        <inlineHelpText>The Business Center and Access user name</inlineHelpText>
        <label>User Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/JobFeedSFtoJiveBatchable.cls
global class JobFeedSFtoJiveBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts{
	    
    global Set<Id> feedIds = new Set<Id>();
    
    global JobFeedSFtoJiveBatchable(Set<Id> feedIds) {
        this.feedIds = feedIds;
    }

   	global Database.QueryLocator start(Database.BatchableContext BC) {
      	return Database.getQueryLocator([SELECT Id, Name, fs_description__c, fs_url__c, rs_recipientAccount__c, rs_recipientLead__c FROM Feed__c WHERE Id IN :feedIds]);
    }

   	global void execute(Database.BatchableContext BC, List<Feed__c> scope) {
        Set<Id> accountIds = new Set<Id>();
    	Set<Id> leadIds = new Set<Id>();
        
        Map<Id, Account> accountMap = new Map<Id, Account>();
    	Map<Id, Lead> leadMap = new Map<Id, Lead>();
        String jiveActionJSON;
        
        for(Feed__c feed : scope) {
            if(feed.rs_recipientAccount__c != Null) {
                accountIds.add(feed.rs_recipientAccount__c);
            }
            else if(feed.rs_recipientLead__c != Null) {
                leadIds.add(feed.rs_recipientLead__c);
            }
        }
        
        if(accountIds.size() > 0) {
            for(Account acct : [SELECT Id, MBOAccess__c, fs_userName__pc FROM Account WHERE MBOAccess__c != false AND fs_userName__pc != Null and Id in : accountIds]) {
                accountMap.put(acct.Id, acct);
            }
        }
        
        if(leadIds.size() > 0) {
            for(Lead lead : [SELECT Id, MBOAccess__c, Username__c FROM Lead WHERE MBOAccess__c != false AND Username__c != null and Id in :leadIds]) {
                System.debug('Lead: ' + lead);
                leadMap.put(lead.Id, lead); 
            }
        }
         
//        List<Feed__c> feedToDelete = new List<Feed__c>();
        
        String JiveURL = JiveSettings__c.getValues('JiveURL').Value__c;
        
        for(Feed__c feed : scope) {
            
            String personUserName;
           
            if(feed.rs_recipientAccount__c != Null) {
                personUserName = accountMap.get(feed.rs_recipientAccount__c).fs_userName__pc;
            }
            else if(feed.rs_recipientLead__c != Null) {
                personUserName = leadMap.get(feed.rs_recipientLead__c).Username__c;
            }
            
            String JIVEPersonURL;
            String jiveResponse = '';
            
            JIVEPersonURL = JiveURL + '/people/username/'+ personUserName ;
            JIVEPersonURL +='?fields=ID,name.givenName,name.familyName,emails,tags,jive.profile.Title,';
            JIVEPersonURL +='jive.username&filter=search()';

            try {
                HttpRequest req = new HttpRequest();
                req.setMethod('GET');
                String username = JiveSettings__c.getValues('Jive Username').Value__c; //'api01';
                String password = JiveSettings__c.getValues('Jive Password').Value__c;//'r8*&!$4*g40XpRsYUw0I';
                Blob headerValue = Blob.valueOf(username + ':' + password);
                String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
                req.setHeader('Authorization', authorizationHeader);
                req.setHeader('Accept', 'application/json');
                req.setEndPoint(JIVEPersonURL);
                
                Http http = new Http();
                
                HTTPResponse res;
                
                if (!Test.isRunningTest()) { 
                	res = http.send(req);
                
                	jiveResponse = res.getBody();                    
                }
				else {
                	jiveResponse = '{  \"name\" : {    \"givenName\" : \"Api01\",    \"familyName\" : \"User01\",    \"formatted\" : \"Api01 User01\"  },  \"type\" : \"person\",  \"tags\" : [ \"testing\", \"developing\" ],  \"jive\" : {    \"username\" : \"stevej\",    \"profile\" : [ {      \"value\" : \"I work with the MBO as a salesforce developer.\",      \"jive_label\" : \"What do you do?\"    } ]  },  \"emails\" : [ {    \"value\" : \"webmaster@mbopartners.com\",    \"type\" : \"work\",    \"jive_label\" : \"Email\",    \"primary\" : true  } ],  \"id\" : \"12856\"}';
                }
                
                system.debug('jiveres: ' + jiveResponse);
                system.debug('feed: ' + feed);
                system.debug('URL: ' + JiveURL);
                JiveAction jiveAction = JobFeedSFToJiveBatchableHelper.generateJiveAction(jiveResponse, feed, JiveURL);
                
                if(jiveAction != Null) {
					jiveActionJSON = JobFeedSFToJiveBatchableHelper.serializeJiveAction(jiveAction);
                }
                
                system.debug('jiveActionJSON: '+ jiveActionJSON);
                
                if(jiveActionJSON != '') {
                    JIVEPersonURL = JiveURL + '/activities';
                    
                    HttpRequest req2 = new HttpRequest();
                    req2.setMethod('POST');
                    
                    req2.setHeader('Authorization', authorizationHeader);
                    req2.setHeader('Accept', 'application/json');
                    req2.setHeader('Content-Type', 'application/json');
                    req2.setEndPoint(JIVEPersonURL);
                    req2.setBody(jiveActionJSON);
                    
                    Http http2 = new Http();
                    HTTPResponse res2;
                    if (!Test.isRunningTest()) { 
                    	res2 = http2.send(req2);
                        jiveResponse = res2.getBody();
                        
                        system.debug('jiveResponse:' + jiveResponse);
                    	if(res2.getStatus() == 'Created') {
//							feedToDelete.add(feed);  
                    	}    
                    }
                    else {
//                    	feedToDelete.add(feed);    
                    }
                }
            }
            catch(Exception ex) {
                System.debug('Exception: ' + ex);   
            }
        }
        
//        if(feedToDelete.size() > 0) {
//        	delete feedToDelete;    
//        }
    }
        
   	global void finish(Database.BatchableContext BC){ 
   	}
}