org_unpackaged/standard/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>fs_facebook__c</fullName>
        <label>Facebook</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fs_industryExpertise__c</fullName>
        <label>Industry Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>Place holder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aerospace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apparel &amp; Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architectural and Design Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcasting, Music, &amp; Film</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Packaged Goods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy &amp; Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment &amp; Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gaming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government &amp; Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare Information Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality &amp; Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology Services</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>fs_linkedin__c</fullName>
        <label>LinkedIn</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fs_overview__c</fullName>
        <label>Overview</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fs_skills__c</fullName>
        <label>Skills</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fs_twitter__c</fullName>
        <label>Twitter</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

org_unpackaged/unpackaged/classes/JiveToSFLeadUpdateHelper.cls
public class JiveToSFLeadUpdateHelper{

    public static Lead processJiveResponse(Lead leadRec, String jiveResponse) {
    	// invalid jason response... https://developers.jivesoftware.com/community/thread/2153  
        jiveResponse = jiveResponse.Replace('throw \'allowIllegalResourceCall is false.\';', '');    
        jiveResponse = jiveResponse.Replace('null', '');
        //jiveResponse = jiveResponse.Replace('Contract Talent management, Entrepreneurship, General Business Consulting, Management and Finance.', '');
        
       
        System.debug('Request Body: ' + jiveResponse);
        
        //JSONParser parser = JSON.createParser(jiveResponse);
        json2apex personRecord=json2apex.parse(jiveResponse);
        //JivePersonObject2 personRecord = (JivePersonObject2) System.JSON.deserialize(jiveResponse, JivePersonObject2.class);
        System.debug('personRecord: ' + personRecord);
        
        //String IndustryExpertise = personRecord.JIVE.getProfileByName('Industries').replace('(', '').replace(')', '').replace(',', ';').replaceAll('\\s+', '');
        //String IndustryExpertise = personRecord.JIVE.getProfileByName('Industries').replace('(', '').trim().replace(')', '').replace(',', ';').trim();
        //system.debug('industriesex: ' + IndustryExpertise);
        
        String Tags = String.valueof(personRecord.tags);
        system.debug('Tags: ' + Tags);
        if( Tags != null ){
            system.debug('NOT:');
            Tags = Tags.replace('(', '').replace(')','').trim(); 
        }
        
        
        if(leadRec.Title != personRecord.JIVE.getProfileByName('Title') ||
           leadRec.fs_skills__c != Tags ||
           leadRec.fs_overview__c != personRecord.JIVE.getProfileByName('What do you do?') ||
           leadRec.fs_facebook__c != personRecord.JIVE.getProfileByName('Facebook') ||
           leadRec.fs_twitter__c != personRecord.JIVE.getProfileByName('Twitter') ||
           //leadRec.fs_industryExpertise__c != IndustryExpertise ||
           leadRec.fs_linkedin__c != personRecord.JIVE.getProfileByName('Linkedin')) {
               
			leadRec.Title = personRecord.JIVE.getProfileByName('Title');
            leadRec.fs_skills__c = Tags;       
			leadRec.fs_overview__c = personRecord.JIVE.getProfileByName('What do you do?');
			leadRec.fs_facebook__c = personRecord.JIVE.getProfileByName('Facebook');
			leadRec.fs_twitter__c = personRecord.JIVE.getProfileByName('Twitter');
			leadRec.fs_linkedin__c = personRecord.JIVE.getProfileByName('Linkedin');
               
            //leadRec.fs_industryExpertise__c = IndustryExpertise;
            //system.debug('testindustries: ' + leadRec.fs_industryExpertise__c);
			return leadRec;
		}
        
        return null;
    }
}