org_unpackaged/standard/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Manager__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Allows the user to reference the EM for this record</description>
        <inlineHelpText>Reference the EM for this record</inlineHelpText>
        <label>Enrollment Manager</label>
        <referenceTo>My_Biz_Office_User__c</referenceTo>
        <relationshipLabel>EM Leads</relationshipLabel>
        <relationshipName>EM_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Persona__c</fullName>
        <description>Allows the user to select the persona for this record</description>
        <inlineHelpText>Please select the main persona for this record www.mbopartners.com</inlineHelpText>
        <label>Persona</label>
        <picklist>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioned Professionals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freelancer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Persona__c</fullName>
        <description>Allows the user to select the Sub-Persona for this record</description>
        <inlineHelpText>Please select the Sub-Persona for this record</inlineHelpText>
        <label>Sub-Persona</label>
        <picklist>
            <controllingField>Persona__c</controllingField>
            <picklistValues>
                <fullName>Professional Service Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobby IC (Financially Independent)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Retired Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependent Retired Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fresh Lay-off/Job Hunter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC Newbie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Considering IC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Considering IC (Actively Searching Vendors/Way to Incorporate)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forced Fresh Lay-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forced PSC Newbie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Just Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasoned CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Broker or Group Practice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Established Freelancer Primarily with Business Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Established Freelancer with Consumer Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freelancer Primarily with Business Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freelancer with Consumer Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newbie Freelancer Primarily with Business Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newbie Freelancer with Consumer Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker that is an MBO Exec</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker that is an MBO Sub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBO Corp Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Company that Uses 1099 Workers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Company Needing Payroll (Primarily NSE Workers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Company Needing Payroll</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rs_BM__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Manager</label>
        <referenceTo>My_Biz_Office_User__c</referenceTo>
        <relationshipLabel>Inquiries</relationshipLabel>
        <relationshipName>Inquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/My_Biz_Office_User__c.object
<CustomObject>
    <description>This object is used to display all MBO employees</description>
    <label>MBO User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MBO Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SetBMForTransitionTriggerTest.cls
@isTest
private class SetBMForTransitionTriggerTest
{
    static testMethod void insertAndUpdate() 
    {
		//instantiate the data
//        List<Lead> inquiries = new List<Lead>();
//        My_Biz_Office_User__c a = new My_Biz_Office_User__c();
//        a.name='Sara Conde';
//        My_Biz_Office_User__c b = new My_Biz_Office_User__c();
//        b.name='Nicolette Taylor';
//        insert a;
//        insert b;	
//        for (Integer i = 1; i <=20; i++)
//        {
//        	inquiries.add(new Lead(FirstName='Test'
//        						  ,LastName='Inquiry' + i
//        						  ,Enrollment_Manager__c=b.id
//        					      ,Status='Inquiry'));
//        }
//        for(Lead newInquiry : [SELECT id, name, Enrollment_Manager__c, Status
//        					   FROM Lead
//        					   WHERE Id
//       					   IN :inquiries]){
//					      		  	insert(newInquiry);
//        					   }
//
		//update the data
//        for(Lead change : [SELECT id, name, Enrollment_Manager__c, rs_BM__c, Status 
//        				   FROM Lead
//        				   WHERE Id
//         				   IN :inquiries]){
//        					  	change.Status='Pending';
//      	}
//        for(Lead newInquiry : [SELECT id, name, Enrollment_Manager__c, Status
//        					   FROM Lead
//        					   WHERE Id
//        					   IN :inquiries]){
//					      		  	update(newInquiry);
//        					   }
//
		//test the data
//        for(Lead updated : [SELECT id, name, Enrollment_Manager__c, rs_BM__c 
//        					FROM Lead
//        					WHERE Id
//        					IN :inquiries]){
//                				System.assertEquals(updated.rs_BM__c,updated.Enrollment_Manager__c);
//    	}
    	
    			//instantiate the data
        //My_Biz_Office_User__c a = new My_Biz_Office_User__c();
        //a.name='Sara Conde';
        My_Biz_Office_User__c b = new My_Biz_Office_User__c(name='Nicolette Taylor');
        //insert a;
        insert b;
        System.debug('MBO_User.id=' + b.id + ', MBO_User.name=' + b.name);	
        List<Lead> inquiries = new List<Lead>();
        for (Integer i = 1; i <=20; i++)
        {
        	inquiries.add(new Lead(FirstName='Test'
        						  ,LastName='Inquiry' + i
        						  ,Enrollment_Manager__c=b.id
        					      ,Status='Inquiry'
        					      ,Persona__c='Consultant'
        					      ,Sub_Persona__c='Professional Service Consultant'));
        }
        insert inquiries;
        for(Lead updated : inquiries)
        {
       		System.debug('Lead ID=' + updated.id + ' BM ID=' + updated.rs_BM__c + ' EM ID=' + updated.Enrollment_Manager__c);
        	updated.Status='Pending';
        }
      	update inquiries;
		//test the data
        for(Lead updated : [SELECT id, name, Enrollment_Manager__c, rs_BM__c, status 
        					FROM Lead
        					WHERE Id
        					IN :inquiries])
        {
        	System.debug('Lead ID=' + updated.id + ' Status=' + updated.Status + ' BM ID=' + updated.rs_BM__c + ' EM ID=' + updated.Enrollment_Manager__c);
        	System.assertEquals(updated.Enrollment_Manager__c,updated.rs_BM__c);
    	}
	}
}