org_unpackaged/standard/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Associate_Status__c</fullName>
        <description>Used to allow the MBO system to update where the associate is in their life cycle</description>
        <inlineHelpText>Updated by the MBO system to display where the associate is in their life cycle</inlineHelpText>
        <label>Associate Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled (old)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending (old)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enrollment_Manager__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Allows the user to reference the EM for this record</description>
        <inlineHelpText>Reference the EM for this record</inlineHelpText>
        <label>Enrollment Manager</label>
        <referenceTo>My_Biz_Office_User__c</referenceTo>
        <relationshipLabel>EM Leads</relationshipLabel>
        <relationshipName>EM_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/My_Biz_Office_User__c.object
<CustomObject>
    <description>This object is used to display all MBO employees</description>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user that is the same person as the MBO user</description>
        <inlineHelpText>Reference the Salesforce user that is the same as this MBO user</inlineHelpText>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MBO_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MBO User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MBO Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

org_unpackaged/unpackaged/objects/Task_List__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To_MBO_User_Field_Name__c</fullName>
        <label>Assign To MBO User Field Name</label>
        <picklist>
            <picklistValues>
                <fullName>Enrollment_Manager__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rs_opsAdmin__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rs_qualAdvisor__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assign the Task to a specific User. If it is blank then assign the Task to the Lead Owner.</description>
        <label>Assign To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Task_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Due Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <description>Add API name of the parent field so that the system automatically updates the corresponding SLA completed field on the parent object.</description>
        <label>Parent Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority of the Task.</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_To_Update_Parent_Field__c</fullName>
        <description>Update the parent object only if the Task status is none or the selected options.</description>
        <label>Status To Update Parent Field</label>
        <picklist>
            <picklistValues>
                <fullName>Attempted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the task</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Task Type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Receive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Task List</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

org_unpackaged/unpackaged/objects/Task_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Child Task</label>
        <referenceTo>Task_List__c</referenceTo>
        <relationshipLabel>Task Relationship (Child Task)</relationshipLabel>
        <relationshipName>Task_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Associate_Status__c</fullName>
        <description>WhoId associate status</description>
        <label>Parent Associate Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled (old)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending (old)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Parent_Task_Status__c</fullName>
        <description>Validate Parent Task Status and create subsequent task.</description>
        <label>Parent Task Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Parent_Task__c</fullName>
        <label>Parent Task</label>
        <referenceTo>Task_List__c</referenceTo>
        <relationshipLabel>Task Relationship</relationshipLabel>
        <relationshipName>Parent_Task</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Relationship</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Task Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Relationship</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskHelper.cls
/**********************************************************
 * Description      : Task Helper class
 * @author          : Kiran Kumar
 * @date            : May 21, 2013
 * Copyright 2013 MBO Partners. All rights reserved.
 **********************************************************/

public with sharing class TaskHelper {

	private static set<Id> processesTaskIds = new set<Id>(); 

	private static map<String, TaskList> mapParentSubjectToTaskList = new map<String, TaskList>();
	public static map<String, TaskList> getTaskList() {
		//map<String, list<Task_List__c>> mapParentSubjectToChildTasks = new map<String, list<Task_List__c>>();

		if (mapParentSubjectToTaskList == null || mapParentSubjectToTaskList.isEmpty()) {
			for (Task_List__c tl : [select Id, Name, Subject__c, Parent_Field_Name__c, Status_To_Update_Parent_Field__c,
											(select Id, Parent_Task__c, Parent_Task_Status__c, Parent_Associate_Status__c,
												Child_Task__c, Child_Task__r.Name, Child_Task__r.Subject__c, Child_Task__r.Type__c, Child_Task__r.Priority__c,
												Child_Task__r.Assign_To__c, Child_Task__r.Assign_To_MBO_User_Field_Name__c, Child_Task__r.Due_Days__c 
											from Parent_Task__r
											where IsActive__c = true)
								 	from  	Task_List__c
								 	where	IsActive__c = true]) {

				mapParentSubjectToTaskList.put(tl.Subject__c, new TaskList(tl));
			}
		}

		return mapParentSubjectToTaskList;
	}

	private static set<String> setMBOUserFields = new set<String>{};
	private static String getTaskListFields() {

		String leadFields = '';
		set<String> setLeadFields = new set<String>{'Associate_Status__c', 'IsConverted'};

		getTaskList();
		for (TaskList tl : mapParentSubjectToTaskList.values()) {
			if (tl.parentTaskList.Parent_Field_Name__c != null) setLeadFields.add(tl.parentTaskList.Parent_Field_Name__c);

			for (Task_Relationship__c trel : tl.childTaskRelations) {
				if (trel.Child_Task__r.Assign_To_MBO_User_Field_Name__c != null) {
					setLeadFields.add(trel.Child_Task__r.Assign_To_MBO_User_Field_Name__c);
					setMBOUserFields.add(trel.Child_Task__r.Assign_To_MBO_User_Field_Name__c);
				}
			}
		}

		if (!setLeadFields.isEmpty()) {
			for (String fieldName : setLeadFields) {
				leadFields += (leadFields != '' ? ', ' : '') + fieldName;
			}
		}
		//system.debug('\n ### leadFields ' + leadFields);

		return leadFields;
	}

	public static void evaluateTasks(map<Id, Task> mapNewTasks, map<Id, Task> mapOldTasks) {

		try {
			map<Id, Lead> mapLeads = new map<Id, Lead>();
			map<Id, Lead> leads_To_Update = new map<Id, Lead>();
			map<Id, My_Biz_Office_User__c> mapMBOUsers = new map<Id, My_Biz_Office_User__c>();
			list<Task> tasks_To_Insert = new list<Task>();
	
			for (Task t : mapNewTasks.values()) {
				if (!processesTaskIds.contains(t.Id) && Util.RecordOf(t.whoId, 'Lead') && (t.Status != mapOldTasks.get(t.Id).Status || t.Subject != mapOldTasks.get(t.Id).Subject)) {
					if (mapParentSubjectToTaskList == null || mapParentSubjectToTaskList.isEmpty()) getTaskList();
	
					if (mapParentSubjectToTaskList.containsKey(t.Subject)) {
						mapLeads.put(t.whoId, null);
					}
				}
			}
	
			if (!mapLeads.isEmpty()) {
				set<Id> leadIds = mapLeads.keySet();
				String soql = 'Select Id, ' + getTaskListFields() + ' from Lead where Id in : leadIds';
				system.debug('\n ### soql ' + soql);
				for (Lead l : Database.query(soql)) {
					mapLeads.put(l.Id, l);
	
					//if (l.Enrollment_Manager__c != null) mapMBOUsers.put(l.Enrollment_Manager__c, null);
					for (String fieldName : setMBOUserFields) {
						Id lookupFieldValue = (Id) l.get(fieldName);
						if (lookupFieldValue != null) mapMBOUsers.put(lookupFieldValue, null);
					}
				}
				system.debug('\n ### mapLeads ' + mapLeads.size() + ' => ' + mapLeads);
	
				if (!mapMBOUsers.isEmpty()) mapMBOUsers = new  map<Id, My_Biz_Office_User__c>([select Id, Salesforce_User__c from My_Biz_Office_User__c where Id in : mapMBOUsers.keySet() and Salesforce_User__c != null and Salesforce_User__r.isActive = true]);
				system.debug('\n ### mapMBOUsers ' + mapMBOUsers.size() + ' => ' + mapMBOUsers);
			}
	
			for (Task t : mapNewTasks.values()) {
				if (!processesTaskIds.contains(t.Id) && Util.RecordOf(t.whoId, 'Lead') && (t.Status != mapOldTasks.get(t.Id).Status || t.Subject != mapOldTasks.get(t.Id).Subject)) {
	
					if (mapParentSubjectToTaskList.containsKey(t.Subject)) {
						TaskList parentTask = mapParentSubjectToTaskList.get(t.Subject);
						Task_List__c parentTaskList = parentTask.parentTaskList;
						Lead ld = mapLeads.get(t.WhoId);

						// parent field updates
						if (!ld.IsConverted && parentTaskList.Parent_Field_Name__c != null && (parentTaskList.Status_To_Update_Parent_Field__c == null || Util.containsIgnoreCase(t.Status, parentTaskList.Status_To_Update_Parent_Field__c.split(';')))) {
							if (!leads_To_Update.containsKey(ld.Id)) leads_To_Update.put(ld.Id, new Lead(Id=ld.Id));
							if (ld.get(parentTaskList.Parent_Field_Name__c) == null && leads_To_Update.get(ld.Id).get(parentTaskList.Parent_Field_Name__c) == null) leads_To_Update.get(ld.Id).put(parentTaskList.Parent_Field_Name__c, system.today()); 
						}

						// create subsequent tasks
						for (Task_Relationship__c trel : parentTask.childTaskRelations) {
							//if ( (trel.Parent_Task_Status__c == null || (trel.Parent_Task_Status__c != null && Util.containsIgnoreCase(t.Status, trel.Parent_Task_Status__c.split(';')) && !Util.containsIgnoreCase(mapOldTasks.get(t.Id).Status, trel.Parent_Task_Status__c.split(';')))) &&
							//	   (trel.Parent_Associate_Status__c == null || (trel.Parent_Associate_Status__c != null && Util.containsIgnoreCase(ld.Associate_Status__c, trel.Parent_Associate_Status__c.split(';')))) )
							if ( (trel.Parent_Task_Status__c == null || (Util.containsIgnoreCase(t.Status, trel.Parent_Task_Status__c.split(';')) && !Util.containsIgnoreCase(mapOldTasks.get(t.Id).Status, trel.Parent_Task_Status__c.split(';')))) &&
								 (trel.Parent_Associate_Status__c == null || !Util.containsIgnoreCase(ld.Associate_Status__c, trel.Parent_Associate_Status__c.split(';'))) ) {
								Task_List__c childTaskList = trel.Child_Task__r;
	
								Id ownerId = trel.Child_Task__r.Assign_To__c;
								ownerId = ownerId == null && trel.Child_Task__r.Assign_To_MBO_User_Field_Name__c != null && mapMBOUsers.containsKey((Id) ld.get(trel.Child_Task__r.Assign_To_MBO_User_Field_Name__c)) ? mapMBOUsers.get((Id) ld.get(trel.Child_Task__r.Assign_To_MBO_User_Field_Name__c)).Salesforce_User__c : null;
								if (ownerId == null && MBOPartnersHelper.MBOAdminUser != null) ownerId = MBOPartnersHelper.MBOAdminUser.Id;
								//if (ownerId == null) ownerId = ld.OwnerId;
								Date activityDate = system.today().addDays(Integer.valueOf(trel.Child_Task__r.Due_Days__c==null ? 0 : trel.Child_Task__r.Due_Days__c)); 
	
								processesTaskIds.add(t.Id);
								tasks_To_Insert.add(new Task(WhoId=ld.Id, Subject=childTaskList.Subject__c, Type=childTaskList.Type__c, Priority=childTaskList.Priority__c, OwnerId=ownerId, ActivityDate=activityDate, IsReminderSet=true, ReminderDateTime=activityDate));	//system.now().addMinutes(2)
							}
						}
					}
				}
			}

			system.debug('\n ### tasks_To_Insert ' + tasks_To_Insert.size() + ' => ' + tasks_To_Insert);
			if (!tasks_To_Insert.isEmpty()) insert tasks_To_Insert;
	
			system.debug('\n ### leads_To_Update ' + leads_To_Update.size() + ' => ' + leads_To_Update);
			if (!leads_To_Update.isEmpty()) update leads_To_Update.values();

		} catch (DmlException ex) {
			mapNewTasks.values()[0].addError(ex.getDmlMessage(0));
		}
	}

	// TaskList wrapper class
	public with sharing class TaskList {
		public Task_List__c parentTaskList						{get; set;}
		public list<Task_Relationship__c> childTaskRelations	{get; set;}

		public TaskList(Task_List__c taskList) {
			this.parentTaskList = taskList;
			if (taskList != null && taskList.Parent_Task__r != null) this.childTaskRelations = taskList.Parent_Task__r;
			if (this.childTaskRelations == null) this.childTaskRelations = new list<Task_Relationship__c>();
		}
	}
}